// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qigaxtsiygecgqmebkbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpZ2F4dHNpeWdlY2dxbWVia2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTQ0ODksImV4cCI6MjA3MjIzMDQ4OX0.OaztSXFhjVEYMGdQtOdUTEIFWGLHxLuac_-gyYF7XJs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});